const { launch } = require('./browser')
const { execSync } = require('child_process')
const B = 'http://localhost:3000'
const sql = (q) => execSync(`psql -q -h 127.0.0.1 -p 55432 -U postgres -tAc "${q.replace(/"/g, '\\"')}"`).toString().trim()
let pass = 0, fail = 0; const ok = (c, m) => { c ? pass++ : fail++; console.log(c ? '  ✓' : '  ✗', m) }
const pad = (n) => String(n).padStart(2, '0')
const day = (off) => { const d = new Date(); d.setDate(d.getDate() + off); return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}` }
;(async () => {
  const tag = Date.now().toString().slice(-5)
  const X = sql(`insert into patients (full_name, phone) values ('Booker ${tag}', '0100${tag}11') returning id`)
  const W = sql(`insert into patients (full_name, phone) values ('Walkin ${tag}', '0100${tag}22') returning id`)
  const T = sql(`insert into patients (full_name) values ('Today ${tag}') returning id`)
  // someone already booked tomorrow 10:30 in Clinic 1
  sql(`insert into appointments (patient_id, scheduled_at, clinic_id) values ((select id from patients where full_name like 'Patient 5%' limit 1), '${day(1)} 10:30'::timestamp at time zone 'UTC', (select id from clinics order by sort_order limit 1))`)
  // booked for later today with no clinic
  const Tappt = sql(`insert into appointments (patient_id, scheduled_at) values ('${T}', now() + interval '1 hour') returning id`)

  const b = await launch()
  const p = await (await b.newContext({ viewport: { width: 1280, height: 900 }, timezoneId: 'UTC' })).newPage()
  p.on('pageerror', (e) => { fail++; console.log('  ✗ page error', e.message) })
  await p.goto(B + '/login'); await p.fill('input[name=email]', 'reception@test.local'); await p.fill('input[name=password]', 'Passw0rd!')
  await Promise.all([p.waitForURL((u) => !u.pathname.startsWith('/login')), p.getByRole('button', { name: 'Enter Clinic' }).click()])

  console.log('Appointments page: book for tomorrow, clinic decided on arrival')
  await p.goto(B + '/appointments', { waitUntil: 'load' })
  await p.getByPlaceholder('Search name, phone, or file #...').fill(`Booker ${tag}`)
  await p.getByRole('button', { name: new RegExp(`Booker ${tag}`) }).click()
  await p.getByRole('button', { name: 'Tomorrow' }).click()
  await p.waitForTimeout(1200)
  const dayList = await p.locator('text=Booked that day:').locator('..').innerText()
  ok(/10:30/.test(dayList), 'shows what is already booked that day: ' + dayList.replace(/\n/g, ' ').slice(0, 90))
  await p.getByLabel('Time').fill('10:30')
  ok(await p.getByText(/already booked around then/).isVisible(), 'warns when the time is already taken')
  await p.getByLabel('Time').fill('11:15')
  const cardText = await p.locator('div.bg-white.rounded-card', { hasText: 'Book Appointment' }).innerText(); ok(!/What for|min\b|this computer/i.test(cardText), 'no length, no "What for", no "this computer"')
  ok(await p.getByRole('button', { name: 'Decide when they arrive' }).evaluate((e) => e.className.includes('bg-teal')), '"Decide when they arrive" is the default')
  await p.screenshot({ path: require('path').join(__dirname, '..', '.run', 'shots', 'booking-panel.png'), fullPage: true })
  await p.getByRole('button', { name: /^Book · / }).click()
  await p.getByText(new RegExp(`Booker ${tag} booked for`)).waitFor({ timeout: 10000 })
  const row = sql(`select to_char(scheduled_at at time zone 'UTC', 'YYYY-MM-DD HH24:MI') || '|' || coalesce(clinic_id::text, 'none') || '|' || coalesce(notes, '') from appointments where patient_id='${X}'`)
  ok(row === `${day(1)} 11:15|none|`, 'saved: tomorrow 11:15, no clinic yet — ' + row)

  console.log('Same patient again the same day')
  await p.getByPlaceholder('Search name, phone, or file #...').fill(`Booker ${tag}`)
  await p.getByRole('button', { name: new RegExp(`Booker ${tag}`) }).click()
  await p.getByRole('button', { name: 'Tomorrow' }).click(); await p.getByLabel('Time').fill('16:00')
  await p.getByRole('button', { name: /^Book · / }).click()
  await p.getByText(/already booked for/).waitFor({ timeout: 10000 }).catch(() => {})
  ok(await p.getByText(/already booked for/).isVisible() && sql(`select count(*) from appointments where patient_id='${X}'`) === '1', 'asks before a second booking the same day')
  await p.getByRole('button', { name: 'Yes, book this one too' }).click(); await p.waitForTimeout(1500)
  ok(sql(`select count(*) from appointments where patient_id='${X}'`) === '2', '"Yes" books the second one')

  console.log('Walk-in desk: book a time instead of sending now')
  await p.goto(B + '/reception', { waitUntil: 'load' })
  await p.getByPlaceholder(/name|phone/i).first().fill(`Walkin ${tag}`)
  await p.getByText(`Walkin ${tag}`).first().click()
  await p.getByRole('button', { name: /Continue|Save & continue/ }).first().click()
  await p.getByRole('button', { name: /Book a time instead/ }).click()
  await p.getByRole('button', { name: 'Tomorrow' }).click(); await p.getByLabel('Time').fill('12:00')
  await p.getByRole('button', { name: /^Clinic 2/ }).click()
  await p.getByRole('button', { name: /^Book · / }).click()
  await p.getByText(`Walkin ${tag} is booked`).waitFor({ timeout: 10000 })
  ok(true, 'confirmation shown: "' + (await p.locator('h2', { hasText: 'is booked' }).locator('..').innerText()).replace(/\n/g, ' ').slice(0, 110) + '"')
  ok(await p.getByRole('link', { name: 'Confirm on WhatsApp' }).isVisible(), 'WhatsApp confirmation link offered')
  ok(sql(`select count(*) from appointments a join clinics c on c.id=a.clinic_id where a.patient_id='${W}' and c.name ilike '%2%'`) === '1', 'booked into Clinic 2')

  console.log('Board: patient booked "on arrival" checks in')
  await p.goto(B + '/appointments', { waitUntil: 'load' })
  const card = p.locator('div.rounded-control.border', { hasText: `Today ${tag}` }).first()
  ok(await card.getByText('Clinic: on arrival').isVisible(), 'card shows "Clinic: on arrival"')
  await card.getByRole('button', { name: /Check in/ }).click()
  ok(await card.getByText('Which clinic?').isVisible(), 'Check in asks which clinic')
  await p.screenshot({ path: require('path').join(__dirname, '..', '.run', 'shots', 'board-which-clinic.png'), fullPage: false })
  await card.getByRole('button', { name: /^(C1|Clinic 1)$/ }).click(); await p.waitForTimeout(2000)
  ok(sql(`select status || '|' || (clinic_id is not null) from appointments where id='${Tappt}'`) === 'arrived|true', 'checked in, clinic set')
  console.log(`${pass} passed, ${fail} failed`); await b.close()
})().catch((e) => { console.error(e); process.exit(2) })
