const { launch } = require('./browser')
;(async () => {
  const b = await launch()
  const p = await (await b.newContext({ viewport: { width: 1280, height: 900 }, deviceScaleFactor: 1.5 })).newPage()
  await p.goto('http://localhost:3000/login'); await p.fill('input[name=email]', 'reception@test.local'); await p.fill('input[name=password]', 'Passw0rd!')
  await Promise.all([p.waitForURL((u) => !u.pathname.startsWith('/login')), p.getByRole('button', { name: 'Enter Clinic' }).click()])
  await p.goto('http://localhost:3000/appointments', { waitUntil: 'load' })
  await p.getByPlaceholder('Search name, phone, or file #...').fill('Booker')
  await p.getByRole('button', { name: /Booker/ }).first().click()
  await p.getByRole('button', { name: 'Tomorrow' }).click(); await p.waitForTimeout(1200)
  await p.getByLabel('Time').fill('10:30')
  await p.locator('div.bg-white.rounded-card', { hasText: 'Book Appointment' }).screenshot({ path: require('path').join(__dirname, '..', '.run', 'shots', 'booking-card.png') })
  await b.close()
})()
