const { launch } = require('./browser')
const { execSync } = require('child_process')
const B = 'http://localhost:3000'
const sql = (q) => execSync(`psql -h 127.0.0.1 -p 55432 -U postgres -tAc "${q.replace(/"/g, '\\"')}"`).toString().trim()
const stock = (n) => Number(sql(`select stock from inventory where name='${n}'`))
let pass = 0, fail = 0
const ok = (c, m) => { if (c) { pass++; console.log('  ✓', m) } else { fail++; console.log('  ✗', m) } }
const shots = require('path').join(__dirname, '..', '.run', 'shots') + '/'

async function login(browser, who) {
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
  const page = await ctx.newPage()
  page.on('pageerror', (e) => { fail++; console.log('  ✗ page error:', e.message) })
  await page.goto(B + '/login')
  await page.fill('input[name=email]', `${who}@test.local`)
  await page.fill('input[name=password]', 'Passw0rd!')
  await Promise.all([page.waitForURL((u) => !u.pathname.startsWith('/login'), { timeout: 20000 }), page.getByRole('button', { name: 'Enter Clinic' }).click()])
  return { ctx, page }
}

;(async () => {
  const browser = await launch()
  const restor = sql("select id from containers where name='Restorative'")

  console.log('Reception: closing routine')
  const { page } = await login(browser, 'reception')
  await page.goto(B + '/stock')
  await page.screenshot({ path: shots + '1-overview.png', fullPage: true })
  ok(await page.getByText('0 of 4 checked today').isVisible(), 'overview shows 0 of 4 containers checked')
  ok(!(await page.getByRole('link', { name: 'Set up' }).count()), 'reception has no Set up link')
  await page.goto(B + '/stock/setup')
  ok(!page.url().includes('/stock/setup'), 'reception is kept out of set-up (' + new URL(page.url()).pathname + ')')

  await page.goto(B + '/stock/check/' + restor, { waitUntil: 'networkidle' })
  ok(await page.getByText('Everything is full — done').isVisible(), 'check starts with everything full')
  const plus = (n) => page.getByRole('button', { name: `One more short: ${n}` })
  for (let k = 0; k < 5; k++) await plus('Composite A2').click({ force: true }).catch(() => {})
  ok(await plus('Composite A2').isDisabled(), 'cannot mark more short than the container holds (2)')
  await plus('Cotton rolls').click()
  await plus('Mirror').click()
  await page.locator('div', { hasText: /^Mirror/ }).last()
  // choose "It's missing" for the mirror
  const mirrorRow = page.locator('div.px-4.py-3', { hasText: 'Mirror' })
  await mirrorRow.getByRole('button', { name: 'It’s missing' }).click()
  await page.screenshot({ path: shots + '2-check.png', fullPage: true })
  await page.getByRole('button', { name: /Save — 3 items short/ }).click()
  ok(await page.getByText('Save Restorative?').isVisible(), 'confirmation sheet lists changes before saving')
  await page.screenshot({ path: shots + '3-confirm.png' })
  const before = { comp: stock('Composite A2'), cotton: stock('Cotton rolls'), mirror: stock('Mirror') }
  await page.getByRole('button', { name: 'Yes, save' }).click()
  await page.getByText('Restorative checked').waitFor()
  await page.screenshot({ path: shots + '4-saved.png', fullPage: true })
  ok(stock('Composite A2') === before.comp, `composite (a procedure material) not taken off twice: ${before.comp} → ${stock('Composite A2')}`)
  ok(stock('Cotton rolls') === before.cotton - 1, `cotton rolls refilled from cabinet: ${before.cotton} → ${stock('Cotton rolls')}`)
  ok(stock('Mirror') === before.mirror, 'missing mirror does not change cabinet stock')
  ok(sql("select missing_quantity from container_items ci join containers c on c.id=ci.container_id join inventory i on i.id=ci.inventory_id where c.name='Restorative' and i.name='Mirror'") === '1', 'mirror flagged missing ×1')
  ok(sql(`select last_checked_at is not null from containers where id='${restor}'`) === 't', 'container marked checked')

  await page.getByRole('button', { name: /Undo this check/ }).click()
  await page.getByText('Everything starts as full').waitFor()
  ok(stock('Cotton rolls') === before.cotton, 'undo puts cotton rolls back')
  ok(sql("select missing_quantity from container_items ci join containers c on c.id=ci.container_id join inventory i on i.id=ci.inventory_id where c.name='Restorative' and i.name='Mirror'") === '0', 'undo clears the missing mirror')

  ok(await page.getByRole('button', { name: /Save — 3 items short/ }).isVisible(), 'after undo, the entries are still there to correct')
  await page.reload()
  // Re-do with only the mirror missing, then resolve it
  await plus('Mirror').click()
  await page.locator('div.px-4.py-3', { hasText: 'Mirror' }).getByRole('button', { name: 'It’s missing' }).click()
  await page.getByRole('button', { name: /Save — 1 item short/ }).click()
  await page.getByRole('button', { name: 'Yes, save' }).click()
  await page.getByText('Restorative checked').waitFor()
  ok(await page.getByRole('link', { name: /^Next:/ }).isVisible(), 'saved screen offers the next container')
  await page.goto(B + '/stock')
  ok(await page.getByText('1 of 4 checked today').isVisible(), 'overview now 1 of 4')
  ok(await page.getByText('Missing tools').isVisible(), 'overview lists missing tools')
  await page.screenshot({ path: shots + '5-overview-after.png', fullPage: true })
  await page.goto(B + '/stock/check/' + restor, { waitUntil: 'networkidle' })
  const m0 = stock('Mirror')
  await page.getByRole('button', { name: 'Lost — replaced from cabinet' }).click()
  await page.waitForTimeout(1500)
  ok(stock('Mirror') === m0 - 1, `lost mirror replaced from cabinet: ${m0} → ${stock('Mirror')}`)

  // Other containers: all full with one tap
  for (const name of ['Crown', 'Endo', 'Ortho']) {
    const id = sql(`select id from containers where name='${name}'`)
    await page.goto(B + '/stock/check/' + id)
    await page.getByRole('button', { name: 'Everything is full — done' }).click()
    await page.getByText(`${name} checked`).waitFor()
  }
  await page.goto(B + '/stock')
  ok(await page.getByText('4 of 4 checked today').isVisible(), 'all 4 containers checked')

  console.log('Reception: daily count')
  await page.goto(B + '/stock/count', { waitUntil: 'networkidle' })
  const inputs = page.locator('input[aria-label^="How many"]')
  const n = await inputs.count()
  ok(n === 5, `five items to count today (${n})`)
  const names = []
  for (let k = 0; k < n; k++) names.push((await inputs.nth(k).getAttribute('aria-label')).replace('How many ', ''))
  // First one: way off → must confirm
  const recorded0 = stock(names[0])
  await inputs.nth(0).fill(String(recorded0 * 2 + 50))
  for (let k = 1; k < n; k++) await inputs.nth(k).fill(String(stock(names[k])))
  await page.getByRole('button', { name: 'Save count' }).click()
  await page.waitForTimeout(500)
  ok(await page.getByText('That is quite different from the records').isVisible(), 'a suspicious count asks for a recount')
  ok(stock(names[0]) === recorded0, 'nothing saved until confirmed')
  await page.screenshot({ path: shots + '6-count-flag.png', fullPage: true })
  await page.getByRole('button', { name: 'Recounted — it’s right' }).click()
  await page.getByRole('button', { name: 'Save count' }).click()
  await page.waitForTimeout(3000); console.log('   AFTER SAVE:', (await page.locator('main').innerText()).replace(/\n/g,' | ').slice(0,600))
  await page.getByText('Count saved').waitFor()
  ok(stock(names[0]) === recorded0 * 2 + 50, `count corrected ${names[0]}: ${recorded0} → ${stock(names[0])}`)
  await page.screenshot({ path: shots + '6b-count-saved.png', fullPage: true }); console.log('   BODY:', (await page.locator('main').innerText()).replace(/\n/g,' | ').slice(0,400))
  await page.getByRole('button', { name: /Undo this count/ }).click()
  await page.waitForTimeout(1500)
  ok(stock(names[0]) === recorded0, 'undo count restores the record')

  console.log('Reception: to-order list')
  sql("update inventory set stock = 1 where name in ('Gutta percha','Bonding agent','Gloves (M)')")
  await page.goto(B + '/stock/order', { waitUntil: 'networkidle' })
  await page.screenshot({ path: shots + '7-order.png', fullPage: true })
  ok(await page.getByText('Dental Supply Co').first().isVisible(), 'grouped by supplier')
  ok(await page.getByText('Gutta percha').first().isVisible(), 'low item listed')
  const wa = await page.locator('a[href*="wa.me"]').first().getAttribute('href').catch(() => null)
  ok(!!wa && wa.includes('201001234567'), 'WhatsApp order link to supplier: ' + (wa || '').slice(0, 60))
  const markBtn = page.getByRole('button', { name: /^Mark \d+ ordered/ }).first()
  await markBtn.click()
  await page.waitForTimeout(1500)
  ok(sql("select ordered_at is not null from inventory where name='Gutta percha'") === 't', 'marked as ordered')
  await page.reload()
  await page.screenshot({ path: shots + '8-waiting.png', fullPage: true })
  const g0 = stock('Gutta percha')
  const arrived = page.getByRole('button', { name: /Arrived/ }).first()
  ok(await arrived.isVisible(), 'waiting-for-delivery shows Arrived')
  await arrived.click()
  await page.waitForTimeout(300)
  const confirmBtn = page.getByRole('button', { name: /^(Add|Save|Confirm|Yes)/ }).first()
  if (await confirmBtn.isVisible().catch(() => false)) await confirmBtn.click()
  await page.waitForTimeout(1500)
  console.log('   gutta percha', g0, '→', stock('Gutta percha'), 'ordered_at', sql("select coalesce(ordered_at::text,'null') from inventory where name='Gutta percha'"))

  console.log('Dentist: set-up and stickers')
  const d = await login(browser, 'dentist')
  await d.page.goto(B + '/stock/setup')
  ok(d.page.url().endsWith('/stock/setup'), 'dentist can open set-up')
  await d.page.screenshot({ path: shots + '9-setup.png', fullPage: true })
  await d.page.goto(B + '/stock/setup/labels')
  const qr = await d.page.locator('img, svg').count()
  ok(qr >= 4, `stickers page renders (${qr} images)`)
  await d.page.screenshot({ path: shots + '10-labels.png', fullPage: true })
  const nav = await d.page.goto(B + '/')
  console.log('   dentist at / →', new URL(d.page.url()).pathname)

  console.log('Two phones check the same container at once')
  sql("update containers set last_checked_at = now() - interval '1 day'")
  const endo = sql("select id from containers where name='Endo'")
  const phoneA = page, phoneB = d.page
  await phoneA.goto(B + '/stock/check/' + endo, { waitUntil: 'networkidle' })
  await phoneB.goto(B + '/stock/check/' + endo, { waitUntil: 'networkidle' })
  const kBefore = stock('K-file 25')
  for (const ph of [phoneA, phoneB]) await ph.getByRole('button', { name: 'One more short: K-file 25' }).click()
  await phoneA.getByRole('button', { name: /Save — 1 item short/ }).click()
  await phoneA.getByRole('button', { name: 'Yes, save' }).click()
  await phoneA.getByText('Endo checked').waitFor()
  await phoneB.getByRole('button', { name: /Save — 1 item short/ }).click()
  await phoneB.getByRole('button', { name: 'Yes, save' }).click()
  await phoneB.getByText(/Someone else saved a check/).waitFor({ timeout: 10000 }).catch(() => {})
  ok(await phoneB.getByText(/Someone else saved a check/).isVisible(), 'second phone is told, not saved twice')
  ok(stock('K-file 25') === kBefore - 1, `K-files taken off once: ${kBefore} → ${stock('K-file 25')}`)
  await phoneB.screenshot({ path: shots + '11-second-phone.png', fullPage: true })
  await phoneB.reload({ waitUntil: 'networkidle' })
  ok(await phoneB.getByText(/Already checked today at/).isVisible(), 'after reload: "already checked today at …"')

  console.log('Delivery arrives, then undo')
  sql("update inventory set stock = 1, ordered_at = now(), ordered_quantity = 4 where name = 'Etching gel'")
  await page.goto(B + '/stock/order', { waitUntil: 'networkidle' })
  const row = page.locator('div', { has: page.getByText('Etching gel', { exact: true }) }).filter({ has: page.getByRole('button', { name: 'Arrived' }) }).last()
  await row.getByRole('button', { name: 'Arrived' }).click()
  await page.getByText('Etching gel: 4 added to stock').waitFor()
  ok(stock('Etching gel') === 5, 'delivery of 4 added: 1 → ' + stock('Etching gel'))
  await page.getByRole('button', { name: 'Undo' }).click()
  await page.getByText('Undone').waitFor()
  ok(stock('Etching gel') === 1 && sql("select ordered_at is not null from inventory where name='Etching gel'") === 't', 'undo: back to 1 and waiting for delivery')

  console.log(`\n${pass} passed, ${fail} failed`)
  await browser.close()
  process.exit(fail ? 1 : 0)
})().catch((e) => { console.error(e); process.exit(2) })
